// <auto-generated />
namespace Csharp_Passion_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class teamplayer1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(teamplayer1));
        
        string IMigrationMetadata.Id
        {
            get { return "202306251413118_teamplayer1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
